### ISSUE TITLE
使用gravity-cli prouduct sub 指令獲取的 method只會顯示 INSERT

### ISSUE THREAD

**Issue by TaroBill** [BrobridgeOrg/gravity-cli#8]
版本: [47ca8b6]
重現流程:
1. 啟動 nats-jetstream、gravity-dispatcher
2. 建立data product 和 ruleset
3. 執行 gravity-cli pub 指令
4. 執行 gravity-cli product sub 指令
獲取事件中method 為 INSERT 而非預期的delete
![螢幕擷取畫面 2024-05-17 134745](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/27ad00a5-ab71-444e-b847-9dd646ee9219)
![螢幕擷取畫面 2024-05-17 134804](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/c8a9bff7-a01b-45bc-9f4c-e2684d0e9679)

**Comment by william-wyliang** [comment]
This is supposed to be a printing error. Is that correct, @cfsghost?

**Comment by cfsghost** [comment]
the bug has been addressed in the [gravity-dispatcher](https://github.com/BrobridgeOrg/gravity-dispatcher).

it has been fixed, you can test the latest release from gravity-dispatcher repository with the tag version v0.0.4+.

https://github.com/BrobridgeOrg/gravity-dispatcher/releases/tag/v0.0.4

**Comment by TaroBill** [comment]
- After test the dispatcher v0.04, the bug is still exist.
![image](https://github.com/user-attachments/assets/d62adb5c-80e1-421c-9245-86ba0fd27adf)
- In the product_event.pb.go file, there is an enum that restricts the method value. Maybe it is a display issue.
![image](https://github.com/user-attachments/assets/e5554d88-94ea-4165-9cac-dae733eb45f3)
- Using nats cli to check product. The method value is as expected.
![image](https://github.com/user-attachments/assets/037a8aa3-f3dd-43c5-9b8b-ea64ec29d8a5)

**Comment by william-wyliang** [comment]
@cfsghost, the issue is partially solved. However, the problem still exists elsewhere. Please take a look at it.
@TaroBill, the third snapshot (with "method":"create") above was used to show the part that successfully passed the test, right?

**Comment by Harry-Brobridge** [comment]
@cfsghost @TaroBill Any updates on this issue?

**Comment by TaroBill** [comment]
> [@cfsghost](https://github.com/cfsghost) [@TaroBill](https://github.com/TaroBill) Any updates on this issue?

It still displays incorrect text on gravity-cli.
